M48
; DRILL file {KiCad 7.0.7} date Tue Jan  9 19:06:39 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-09T19:06:39-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X151.865Y-109.41
X151.865Y-115.19
T2
X146.444Y-101.137
X153.444Y-101.137
T0
M30
